# Generated by Django 3.0.7 on 2020-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200612_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateField(auto_now_add=True),
        ),
    ]
