# Generated by Django 3.0.7 on 2020-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_createuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='first_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='last_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
