# Generated by Django 3.0.7 on 2020-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200619_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('body', models.TextField(db_index=True)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateField(auto_now_add=True, verbose_name='date of publication'),
        ),
    ]
