# Generated by Django 3.0.7 on 2020-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200731_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
