# Generated by Django 3.0.7 on 2020-09-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200731_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
