# Generated by Django 3.0.7 on 2020-07-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
