# Generated by Django 3.0.7 on 2020-07-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('body', models.TextField(db_index=True)),
                ('date_pub', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
    ]
